export const FABRICS = [
  "Acrylic",
  "Art Silk",
  "Bamboo",
  "Banarasi Silk",
  "Chambray",
  "Chanderi Cotton",
  "Chanderi Silk",
  "Chiffon",
  "Cotton",
  "Cotton Blend",
  "Cotton Cambric",
  "Cotton Linen",
  "Cotton Silk",
  "Cotton Slub",
  "Crepe",
  "Denim",
  "Dupion Silk",
  "Georgette",
  "Jacquard",
  "Jute Cotton",
  "Jute Khadi",
  "Jute Silk",
  "Khadi Cotton",
  "Khadi Silk",
  "Kora Muslin",
  "Lace",
  "Linen",
  "Mulmul",
  "Muslin",
  "Net",
  "Nylon",
  "Organza",
  "Paper Silk",
  "Pashmina",
  "Poly Chiffon",
  "Poly Crepe",
  "Poly Georgette",
  "Poly Silk",
  "Polycotton",
  "Polyester",
  "Polyster",
  "Rayon",
  "Rayon Slub",
  "Satin",
  "Satin Silk",
  "Shantoon",
  "Silk",
  "Silk Blend",
  "Soft Silk",
  "Super Net",
  "Synthetic",
  "Synthetic Crepe",
  "Taffeta Silk",
  "Tissue",
  "Tussar Silk",
  "Velvet",
  "Vichitra Silk",
  "Viscose",
  "Viscose Rayon",
  "Viscose Silk",
  "Voile",
  "Wool"
];

export const FIT_SHAPES = [
  "A-line",
  "Alia Cut",
  "Anarkali",
  "Angrakha",
  "Assymetrical",
  "C-Cut",
  "Cowl",
  "Crop Top Kurti",
  "Dhoti",
  "Empire",
  "Flared",
  "Front Slit",
  "Gown",
  "Gujrati",
  "High- Slit",
  "High-Low",
  "Jacket Kurta",
  "Jaipuri",
  "Kaftan",
  "Kashmiri",
  "Layered",
  "Lucknowi",
  "Maternity",
  "Maxi Kurta",
  "Naira Cut",
  "Pakistani",
  "Panelled",
  "Pleated",
  "Rajasthani",
  "Sambalpuri",
  "Short",
  "Short Kurti",
  "Shrug Kurti",
  "Straight",
  "Tiered",
  "Tunic"
];

export const LENGTHS = [
  "Above Knee",
  "Knee Length",
  "Below Knee",
  "Calf Length",
  "Mid Calf",
  "Ankle Length",
  "Floor Length"
];

export const NECKS = [
  "Round",
  "V-Neck",
  "Boat",
  "Mandarin",
  "Collar",
  "Shirt Collar",
  "Keyhole",
  "Square",
  "Sweetheart",
  "Scoop",
  "Notch",
  "Paan",
  "Cowl",
  "Shawl",
  "Halter",
  "Off-Shoulder",
  "Tie-Up",
  "Surplice",
  "Court",
  "Horse Shoe",
  "Stylised"
];

export const OCCASIONS = [
  "Casual",
  "Daily Wear",
  "Office Wear",
  "Party Wear",
  "Festive Wear",
  "Wedding Wear",
  "Ethnic Wear",
  "Traditional",
  "Maternity",
  "College Wear",
  "Formal",
  "Vacation"
];

export const PATTERNS = [
  "Solid",
  "Printed",
  "Embroidered",
  "Chikankari",
  "Applique",
  "Embellished",
  "Self Design",
  "Woven Design",
  "Zari Embroidered",
  "Zari Woven",
  "Checked",
  "Striped",
  "Floral",
  "Paisley",
  "Geometric",
  "Abstract",
  "Ethnic Motifs",
  "Colorblocked",
  "Dyed/Washed",
  "Tie & Dye",
  "Bandhani",
  "Leheriya",
  "Animal Print",
  "Polka Dot",
  "Chevron",
  "Ikat"
];

export const SLEEVES = [
  "Long Sleeves",
  "Short Sleeves",
  "Sleeveless",
  "Three-Quarter Sleeves"
];

export const STITCH_TYPES = [
  "Semi-Stitched",
  "Stitched",
  "Unstitched"
];
